version: "3.7"
services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    depends_on:
      - db

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app

  db:
    image: library/mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=macpaw
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    ports:
      - "3308:3306"
